version: "2"
services:
  proxy:
    image: rancher/lb-service-haproxy:v0.6.2
    ports:
      - 80:80/tcp
    stdin_open: true
    tty: true
  api:
    image: fael84/shortener-server:latest
    environment:
      SERVER_ADDR: ":8080"
      REDIS_ADDR:  "persistence:6379"
    links:
      - persistence
    depends_on:
      - persistence
    tty: true
    stdin_open: true
  persistence:
    image: redis:latest
    stdin_open: true
    tty: true
