version: '2'
services:
  proxy:
    scale: 1
    lb_config:
      certs: []
      port_rules:
      - priority: 1
        protocol: http
        service: api
        source_port: 80
        target_port: 8080
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 42
      unhealthy_threshold: 3
      interval: 6000
      strategy: recreate
    start_on_create: true
  api:
    scale: 2
    start_on_create: true
  persistence:
    scale: 1
    start_on_create: true
